[package]
name = "syncrim-clic-rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = "0.11.0"
riscv-rt = "0.12.1"
clic = {git = "https://github.com/onsdagens/clic", branch = "regstack"}
